services:
    backend:
        build:
            context: ./
        restart: always
        labels:
          - 'traefik.enable=true'
          - 'traefik.docker.network=web'
          - 'traefik.http.routers.sandbox_back.rule=Host(`api.sandbox.bleit.ru`)'
          - 'traefik.http.routers.sandbox_back.entrypoints=websecure'
          - 'traefik.http.routers.sandbox_back.tls=true'
          - 'traefik.http.routers.sandbox_back.tls.certresolver=myresolver'
          - 'traefik.http.services.sandbox_back.loadbalancer.server.port=3000'
        networks:
            - web


networks:
    web:
        external: true